status:
	chezmoi re-add
	chezmoi git -- add -u
	chezmoi git -- status

pull:
	chezmoi git -- pull
	chezmoi apply

push:
	chezmoi git -- push

diff:
	chezmoi git -- diff --staged

dl:
	curl -LO https://raw.githubusercontent.com/rupa/z/refs/heads/master/z.sh
